all:
  vars:
    cloudflare_email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') }}"
    cloudflare_api_key: "{{ lookup('env', 'CLOUDFLARE_API_KEY') }}"
    acme_email: "{{ lookup('env', 'CLOUDFLARE_EMAIL') }}"
    time_zone: "Europe/Istanbul"
  hosts:
    app-p01:
      ansible_host: 192.168.1.101
      ansible_user: perim.labz.tr
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    app-p02:
      ansible_host: 192.168.1.102
      ansible_user: perim.labz.tr
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    app-p03:
      ansible_host: 192.168.1.103
      ansible_user: perim.labz.tr
      ansible_ssh_private_key_file: ~/.ssh/id_rsa


  children:
    swarm_manager:
      hosts:
        app-p01
    swarm_nodes:
      hosts:
        app-p01