http:
  routers:
    traefik:
      rule: "Host(`traefik.labz.tr`)"
      entryPoints:
        - websecure
      tls:
        certresolver: myresolver
      service: traefik-dashboard

    metrics:
      rule: "Host(`traefik.labz.tr`) && Path(`/metrics`)"
      entryPoints:
        - websecure
      tls:
        certresolver: myresolver
      service: metrics-service

    pihole:
      rule: "Host(`pihole.labz.tr`)"
      entryPoints:
        - websecure
      tls:
        certresolver: myresolver
      service: pihole-service
    
    n8n:
      rule: "Host(`n8n.labz.tr`)"
      entryPoints:
        - websecure
      tls:
        certresolver: myresolver
      service: n8n-service
    
    homeassistant:
      rule: "Host(`ha.labz.tr`)"
      entryPoints:
        - websecure
      tls:
        certresolver: myresolver
      service: homeassistant-service

  services:
    traefik-dashboard:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"

    metrics-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9100"

    pihole-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.102:8080"

    n8n-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.105:5678"

    homeassistant-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.103:8123"
