name: Update Gatus Configuration

on:
  workflow_dispatch:  
  push:
    paths:
      - 'ansible/playbooks/install-gatus.yml'
      - '.github/workflows/gatus.yml'

jobs:
  run-ansible:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Configure SSH Private Key (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Configure SSH Private Key (Windows)
        if: runner.os == 'Windows'
        run: |
          $sshDir = "$env:USERPROFILE\.ssh"
          New-Item -ItemType Directory -Force -Path $sshDir | Out-Null
          Set-Content -Path "$sshDir\id_rsa" -Value "${{ secrets.SSH_PRIVATE_KEY }}"
        shell: powershell


      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory/hosts.yml playbooks/install-gatus.yml
