name: Update Traefik Configuration
permissions:
  contents: read

on:
  workflow_dispatch:  
  push:
    paths:
      - 'ansible/roles/traefik/**'
      - 'ansible/playbooks/install-traefik.yml'
      - '.github/workflows/traefik.yml'

jobs:
  run-ansible:
    runs-on: Linux
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Configure SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Run Ansible playbook
        run: |
          ssh-keyscan -H 192.168.1.101 >> ~/.ssh/known_hosts
          ansible-playbook -i inventory/hosts.yml playbooks/install_traefik.yml
